### PR TITLE
Added .equals arities for precision comparison and distance. 

### PR DESCRIPTION
**Pull request by gituser768**
Also cleaned up namespaces

### CODE REVIEW

**Comment by alanforr** [comment]
Hello. I appreciate the effort you have made to clean up the code, and your interest in improving the library. However, your new equals function fails to pass tests. If you have the entire project downloaded, you can run the tests by running "lein test" in the project folder. I would be happy to accept a pull request without the changed equal function, or to accept a working version of the changed equality function.

What I mean by a working version is the following. You should write a test illustrating the behaviour you want to see and it should pass.

There is another problem with the code you wrote: it has two versions of the equals function that have the same arity, which is not allowed in Clojure.

**Comment by gituser768** [comment]
I'll fix this up!

**Comment by gituser768** [comment]
I've written a few tests and `lein test` passes for me now. I hope that looks better now

In the future I'll add an additional equals function which uses maxUlps as the comparison instead.

**Comment by alanforr** [comment]
I have merged your commits. Thanks.

**Pull request merged**
